### ISSUE TITLE
python.exe stop working

### ISSUE THREAD

**Issue by zhangzhizz** [mrakgr/Tutorials#2]
@mrakgr hi,i running my theano,but,i just get python.exe stop working,do you know how to deal with it ?

**Comment by mrakgr** [comment]
No, sorry. I haven't used Python in 2 years. This tutorial is something that I did in the past and I never used Theano after that. As a matter of fact, Theano has been discontinued by its development team. I suggest trying Tensorflow or PyTorch if you can. 

Good luck.

**Comment by zhangzhizz** [comment]
@mrakgr ok,thank you for your reply,it is terrible for install theano in windows
